apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-writer
  labels:
    app: db-writer
spec:
  selector:
    matchLabels:
      app: db-writer
  template:
    metadata:
      labels:
        app: db-writer
        tier: web
    spec:
      containers:
      - name: db-writer
        image: abc123/db_writer
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: db-writer
  labels:
    app: db-writer
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: db-writer
