apiVersion: apps/v1
kind: Deployment
metadata:
  name: varowner-letters
  labels:
    app: letters
    owner: varowner
spec:
  selector:
    matchLabels:
      app: letters
      owner: varowner
  template:
    metadata:
      labels:
        app: letters
        tier: web
        owner: varowner
    spec:
      containers:
      - name: letters
        image: gcr.io/windmill-public-containers/abc123/letters
        command: ["node", "/app/index.js"]
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: varowner-letters
  labels:
    app: letters
    owner: varowner
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: letters
    owner: varowner
